export const EmojiData = [
    { emoji: '😀' },
    { emoji: '😃' },
    { emoji: '😄' },
    { emoji: '😁' },
    { emoji: '😆' },
    { emoji: '😅' },
    { emoji: '😂' },
    { emoji: '🤣' },
    { emoji: '😊' },
    { emoji: '😇' },
    { emoji: '🙂' },
    { emoji: '🙃' },
    { emoji: '😉' },
    { emoji: '😌' },
    { emoji: '😍' },
    { emoji: '🥰' },
    { emoji: '😘' },
    { emoji: '😗' },
    { emoji: '😙' },
    { emoji: '😚' },
    { emoji: '😋' },
    { emoji: '😛' },
    { emoji: '😝' },
    { emoji: '😜' },
    { emoji: '🤪' },
    { emoji: '🤨' },
    { emoji: '🧐' },
    { emoji: '🤓' },
    { emoji: '😎' },
    { emoji: '🤩' },
    { emoji: '🥳' },
    { emoji: '😏' },
    { emoji: '😒' },
    { emoji: '😞' },
    { emoji: '😔' },
    { emoji: '😟' },
    { emoji: '😕' },
    { emoji: '🙁' },
    { emoji: '☹️' },
    { emoji: '😣' },
    { emoji: '😖' },
    { emoji: '😫' },
    { emoji: '😩' },
    { emoji: '🥺' },
    { emoji: '😢' },
    { emoji: '😭' },
    { emoji: '😤' },
    { emoji: '😠' },
    { emoji: '😡' },
    { emoji: '🤬' },
    { emoji: '🤯' },
    { emoji: '😳' },
    { emoji: '🥵' },
    { emoji: '🥶' },
    { emoji: '😱' },
    { emoji: '😨' },
    { emoji: '😰' },
    { emoji: '😥' },
    { emoji: '😓' },
    { emoji: '🤗' },
    { emoji: '🤔' },
    { emoji: '🤭' },
    { emoji: '🤫' },
    { emoji: '🤥' },
    { emoji: '😶' },
    { emoji: '😐' },
    { emoji: '😑' },
    { emoji: '😬' },
    { emoji: '🙄' },
    { emoji: '😯' },
    { emoji: '😦' },
    { emoji: '😧' },
    { emoji: '😮' },
    { emoji: '😲' },
    { emoji: '🥱' },
    { emoji: '😴' },
    { emoji: '🤤' },
    { emoji: '😪' },
    { emoji: '😵' },
    { emoji: '🤐' },
    { emoji: '🥴' },
    { emoji: '🤢' },
    { emoji: '🤮' },
    { emoji: '🤧' },
    { emoji: '😷' },
    { emoji: '🤒' },
    { emoji: '🤕' },
    { emoji: '🤑' },
    { emoji: '🤠' },
    { emoji: '😈' },
    { emoji: '👿' },
    { emoji: '👹' },
    { emoji: '👺' },
    { emoji: '🤡' },
    { emoji: '💩' },
    { emoji: '👻' },
    { emoji: '💀' },
    { emoji: '☠️' },
    { emoji: '👽' },
    { emoji: '👾' },
    { emoji: '🤖' },
    { emoji: '🎃' },
];
export const EmojiReaction=[{
    source:require('../media/icon/like_icon.png'),
},
{
    source:require('../media/Dicons/happy-face.png'),
},
{
    source:require('../media/Dicons/smile.png'),
},
{
    source:require('../media/Dicons/heartF.png'),
},
{
    source:require('../media/icon/wow_icon.png'),
},
]
export const reaction = [
    {
        id:"1",
        name:"Like",
        Emoji:require('../media/Dicons/thumb-up.png'),
        type:1
    },
    {
        id:"2",
        name:"Haha",
        Emoji:require('../media/Dicons/happy-face.png'),
        type:2
    },
    {
        id:"3",
        name:"Haha",
        Emoji:require('../media/Dicons/smile.png'),
        type:3
    },
    {
        id:"4",
        name:"Tim",
        Emoji:require('../media/Dicons/heartF.png'),
        type:4
    },
    {
        id:"5",
        name:"Wow",
        Emoji:require('../media/Dicons/wow.png'),
        type:5
    },
    {
        id:"6",
        name:"Angry",
        Emoji:require('../media/Dicons/angry.png'),
        type:6
    },
 
  
]

